---
title: "Stat 333 Project Results"
author: "Aiden Carney, Ellie Brothers, Jonathan Morris, Maxim Yam, Youngwoo Kim"
date: "2024-05-05"
output: html_document
---

# Introduction


# Methodology


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=F, error=F, warning=F, message=F}
# Load packages:
library(dplyr)
library(tidyr)
library(ggplot2)
library(interactions)
library(usmap)
library(knitr)
library(broom)
```

```{r, echo=F, message=F}
# load the data
#data <- read.csv("https://raw.githubusercontent.com/ajcarney/STAT333Project/master/clean_data/data.csv")
data <- read.csv("clean_data/data.csv")
data <- data %>% select(-Perc_Dem, -Perc_Rep) %>% drop_na()
```

```{r, echo=F, message=F, fig.cap="Figure 1: EV Market Penetration vs Log Median Income", fig.align = 'center'}
# Plot log_income
ggplot(data, aes(x=log_income, y = ev_market_penetration)) +
  geom_point(aes(color = gas_regular),position = position_jitter(width = 0.005, height = 0.005), alpha=0.5) +
  geom_smooth(method = "lm") +
  ggtitle("Median Household Income Associated With EV Market Penetration") +
  labs(x = "Log (Median Household Income)", y = "Electric Vehicle Market Penetration") + 
  scale_color_continuous(name = "Average Gas Price ($/gal)") + 
  scale_color_gradient(name = "Average Gas Price ($/gal)",
                       low = "pink",  # lighter color
                       high = "darkred")
```

```{r, echo=F, message=F, fig.cap="Figure 2: EV Market Penetration vs Log Adjusted Income", fig.align = 'center'}
# Plot log (income / RPP)
ggplot(data, aes(x=log_income_adjusted, y = ev_market_penetration)) +
  geom_point(aes(color = gas_regular),position = position_jitter(width = 0.005, height = 0.005), alpha=0.5) +
  geom_smooth(method = "lm") +
  ggtitle("Median Household Income Associated With EV Market Penetration") +
  labs(x = "Log (Median Household Income / RPP)", y = "Electric Vehicle Market Penetration") + 
  scale_color_continuous(name = "Average Gas Price ($/gal)") + 
  scale_color_gradient(name = "Average Gas Price ($/gal)",
                       low = "pink",  # lighter color
                       high = "darkred")
```

```{r, echo=F, message=F, warning=F, fig.cap="Figure 3: Log Adjusted Income by County", fig.align = 'center'}
# Plot log income adjusted on a map
plot_usmap(data = data, values="log_income_adjusted", color = "grey", size = .25, linewidth=0.1) +
  scale_fill_gradient(low = "pink", high = "darkred", na.value = "transparent") +
  theme(legend.position = "right")
```

```{r, echo=F, message=F, warning=F, fig.cap="Figure 4: EV Market Penetration by County", fig.align = 'center'}
# Plot ev market penetration on a map
plot_usmap(data = data, values="ev_market_penetration", color = "grey", size = .25, linewidth=0.1) +
  scale_fill_gradient(low = "pink", high = "darkred", na.value = "transparent") +
  theme(legend.position = "right")
```





```{r, echo=F, message=F}
# Run the model with log income adjusted:
fit <- lm(ev_market_penetration ~ log_income_adjusted*gas_regular + gas_tax + n_charging_locations + log_population + avg_temp + Perc_Adults_Bachelor_Or_Above, data = data)

fit %>% tidy() %>% kable(caption="Figure 5: Linear Model Summary")
```


```{r, echo=F, message=F, fig.cap="Figure 6: Diagnostic Plots", fig.align = 'center'}
# diagnostic plots
par(mfrow = c(2,2))
plot(fit, labels.id = data$county_name)
```


```{r, echo=F, message=F, warning=F, fig.cap="Figure 7: Residuals by County", fig.align = 'center'}
# Plot residuals on a map
data2 <- data %>% mutate(residuals = resid(fit))

plot_usmap(data = data2, values="residuals", color = "grey", size = .25, linewidth=0.1) +
  scale_fill_gradient(low = "pink", high = "darkred", na.value = "transparent") +
  theme(legend.position = "right")
```

# Appendix

#### Code:

```{r get-labels, echo = FALSE}
labs = knitr::all_labels()
labs = setdiff(labs, c("setup", "get-labels"))
```

```{r all-code, ref.label=labs, eval=FALSE}
```

#### Linear Model Summary:

```{r, echo=F}
summary(fit)
```

